const GRAPH='https://raw.githubusercontent.com/SamoTech/skills-tree/main/data/SKILLS_GRAPH.json';const REG='https://raw.githubusercontent.com/SamoTech/skills-tree/main/registry/universal_registry.json';let graph={nodes:[],edges:[]},registry={};let map=new Map(),selected=null;
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
function esc(v){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
function label(n){return n?.name||n?.label||n?.id||''}function domain(n){return n?.category||n?.domain||'Uncategorised'}
function activeNodes(){return graph.nodes.filter(n=>!String(domain(n)).toLowerCase().startsWith('00-sandbox'))}
function deps(id){const out=[],by=[];for(const e of graph.edges||[]){if(e.target===id)out.push(map.get(e.source));if(e.source===id)by.push(map.get(e.target))}return {out:out.filter(Boolean),by:by.filter(Boolean)}}
function showView(id){$$('.view').forEach(v=>v.classList.toggle('active',v.id===id));$$('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));if(id==='explorer')render()}
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>showView(b.dataset.view)));
$('#theme').addEventListener('click',()=>{const d=document.documentElement;d.dataset.theme=d.dataset.theme==='light'?'dark':'light'});
function renderStats(){const n=activeNodes(),e=graph.edges?.length||0,c=new Set(n.map(domain)).size;$('#stats').innerHTML=[[''+n.length,'Skills'],[''+e,'Connections'],[''+c,'Domains'],[''+(registry.implementations?.length||0),'Implementations']].map(x=>'<div class="stat"><strong>'+x[0]+'</strong><span>'+x[1]+'</span></div>').join('');const withE=n.filter(x=>{const d=deps(x.id);return d.out.length||d.by.length}).length;$('#health').innerHTML=[['Coverage',Math.round(withE/n.length*100)+'%'],['Isolated',n.length-withE],['Average edges',n.length?(e/n.length).toFixed(1):'—'],['Runtime',registry.schema_version||'universal registry']].map(x=>'<div class="health-row"><span>'+x[0]+'</span><b>'+x[1]+'</b></div>').join('')}
function initFilters(){const domains=[...new Set(activeNodes().map(domain))].sort((a,b)=>a.localeCompare(b));$('#domain').innerHTML='<option value="all">All domains</option>'+domains.map(x=>'<option>'+esc(x)+'</option>').join('')}
function matches(n){const q=$('#search').value.trim().toLowerCase(),d=$('#domain').value,l=$('#level').value,s=$('#stability').value;if(q&&!([n.id,n.name,n.label,n.category,n.domain,n.layer].filter(Boolean).join(' ').toLowerCase().includes(q)))return false;if(d!=='all'&&domain(n)!==d)return false;if(l!=='all'&&!String(n.level||n.complexity||'').toLowerCase().includes(l))return false;if(s!=='all'&&!String(n.stability||n.status||'').toLowerCase().includes(s))return false;return true}
function render(){const ns=activeNodes().filter(matches);$('#result-count').textContent=ns.length+' skills';$('#skills').innerHTML=ns.map(n=>'<article class="skill-card '+(selected===n.id?'selected':'')+'" data-id="'+esc(n.id)+'"><div class="skill-name">'+esc(label(n))+'</div><div class="skill-id">'+esc(n.id)+'</div><div class="skill-meta"><span>'+esc(domain(n))+'</span><span>'+esc(n.level||n.complexity||'unclassified')+'</span><span>'+esc(n.stability||n.status||'unknown')+'</span></div></article>').join('')||'<div class="panel muted">No skills match the current filters.</div>';$$('.skill-card').forEach(c=>c.addEventListener('click',()=>select(c.dataset.id)))}
function select(id){selected=id;const n=map.get(id);if(!n)return;render();const d=deps(id);const rows=(title,arr)=>'<div class="detail-section"><b>'+title+'</b>'+ (arr.length?arr.map(x=>'<div class="dep"><span>'+esc(label(x))+'</span><code>'+esc(x.id)+'</code></div>').join(''):'<div class="muted">None mapped.</div>')+'</div>';$('#detail').classList.remove('empty');$('#detail').innerHTML='<div class="detail-title"><div><div class="eyebrow">'+esc(domain(n))+'</div><h3>'+esc(label(n))+'</h3><code>'+esc(n.id)+'</code></div><button class="secondary" id="copy">Copy link</button></div><div class="chips"><span>'+esc(n.level||'unclassified')+'</span><span>'+esc(n.stability||'unknown')+'</span><span>'+esc(n.version||'unversioned')+'</span></div>'+rows('Prerequisites / incoming',d.out)+rows('Required by / outgoing',d.by)+'<div class="detail-section"><b>Source</b><div class="muted">'+esc(n.source_file||n.file||'Registry graph')+'</div></div>';$('#copy').onclick=()=>navigator.clipboard?.writeText(location.origin+location.pathname+'#skill='+encodeURIComponent(id))}
['search','domain','level','stability'].forEach(id=>$('#'+id).addEventListener('input',render));$('#random').addEventListener('click',()=>{const ns=activeNodes();select(ns[Math.floor(Math.random()*ns.length)].id)});
function renderRegistry(){const impl=registry.implementations||[];const adapters=registry.adapters||[];$('#registry-cards').innerHTML=(impl.map(x=>'<article class="registry-card panel"><span class="eyebrow">IMPLEMENTATION</span><h3>'+esc(x.name||x.id)+'</h3><div class="kv"><b>ID</b><code>'+esc(x.id)+'</code></div><div class="kv"><b>Skill</b><code>'+esc(x.skill)+'</code></div><div class="kv"><b>Type</b><span>'+esc(x.type)+'</span></div><div class="kv"><b>Status</b><span class="status">'+esc(x.status)+'</span></div><div class="kv"><b>Evidence</b><span>'+esc((x.evidence||[]).length)+' record(s)</span></div></article>').join('')||'')+(adapters.map(x=>'<article class="registry-card panel"><span class="eyebrow">ADAPTER</span><h3>'+esc(x.name||x.id)+'</h3><div class="kv"><b>ID</b><code>'+esc(x.id)+'</code></div><div class="kv"><b>Implementation</b><code>'+esc(x.implementation)+'</code></div><div class="kv"><b>Targets</b><span>'+esc((x.targets||[]).map(t=>t.type+': '+t.id).join(', ')||'—')+'</span></div><div class="kv"><b>Status</b><span class="status">'+esc(x.status)+'</span></div></article>').join(''))||'<div class="panel muted">No registry records found.</div>'}
async function boot(){try{const [g,r]=await Promise.all([fetch(GRAPH).then(x=>x.json()),fetch(REG).then(x=>x.json())]);graph=g;registry=r;activeNodes().forEach(n=>map.set(n.id,n));renderStats();initFilters();renderRegistry();if(location.hash.startsWith('#skill=')){showView('explorer');select(decodeURIComponent(location.hash.slice(7)))} }catch(e){console.error(e);document.querySelector('main').innerHTML='<div class="panel"><h2>Frontend data load failed</h2><p class="muted">'+esc(e.message)+'</p><p class="muted">The UI expects the public GitHub graph and universal registry to be reachable.</p></div>'}}
boot();